- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: yes
  tags: [never, upgrade-os]

- name: Install the latest version of some basic packages
  dnf:
    name:
      - vim
      - bash-completion
    state: latest
  become: yes

- name: Install some required python packages
  pip:
    name: openshift
  become: yes
