- block:
    - name: Create the .conf file to load the modules at bootup
      copy:
        dest: /etc/modules-load.d/crio.conf
        content: |
          overlay
          br_netfilter

    - name: Load the needed kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set up required sysctl params, these persist across reboots. Reload kernel parameters
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        reload: yes
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables

    - name: Setup the devel_kubic_libcontainers_stable repository
      get_url:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/devel:kubic:libcontainers:stable.repo
        dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo

    - name: Setup the devel_kubic_libcontainers_stable_cri-o_1.18 repository
      get_url:
        url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ crio_os }}/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo
        dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo

    - name: Install cri-o
      dnf:
        name: cri-o
        state: latest

    - name: Copy the cri-o config file
      copy:
        src: crio.conf
        dest: /etc/crio/crio.conf

    - name: Enable and start the cri-o service
      systemd:
        daemon_reload: yes
        state: started
        enabled: yes
        name: crio
  become: yes
