- block:
    - name: Setup the kubernetes repository
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
    - name: Install kubeadm
      dnf:
        name: kubeadm-{{ kubeadm_version }}
        state: installed
        disable_excludes: kubernetes
        allow_downgrade: yes
    - name: Install kubelet
      dnf:
        name: kubelet-{{ kubelet_version }}
        state: installed
        disable_excludes: kubernetes
        allow_downgrade: yes
    - name: Install kubectl
      dnf:
        name: kubectl-{{ kubectl_version }}
        state: installed
        disable_excludes: kubernetes
        allow_downgrade: yes
    - name: Enable and start the kubelet service
      systemd:
        state: started
        enabled: yes
        name: kubelet
  become: yes

- name: Create the ~/.kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
- name: Add the kubectl completion to the ~/.bashrc
  vars:
    comment: "# Added by Ansible"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source <(kubectl completion bash)  {{ comment }}"
    create: yes
